### ISSUE TITLE
i want to contribute to cpp

### ISSUE THREAD

**Issue by Reyansh17** [Prem-Kumar-Dev/hacktoberfest2024-project#17]
i will valuable dsa questions ,pls assign me under hacktoberfest2024

**Comment by Prem-Kumar-Dev** [comment]
@Reyansh17 sure

**Comment by Reyansh17** [comment]
thank you i will do it today

**Comment by vaishnavikhairnar3018** [comment]
can you assign this issue to me @Prem-Kumar-Dev
