### ISSUE TITLE
updation in README.md file needed 

### ISSUE THREAD

**Issue by soham0028** [Prem-Kumar-Dev/hacktoberfest2024-project#23]
Hello @Prem-Kumar-Dev 
the current readme file does not contain: 
1. table of contents
2. featured in section 
3. contributors section 
4. back to top button 

Kindly assign me the issue with hacktoberfest accepted labels so my work counts under hacktoberfest

**Comment by Prem-Kumar-Dev** [comment]
@soham0028 sure
